server {
    listen 80;
    server_name to_fill; # Replace with your domain name e.g., your.domain.com

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }

    # Other comfigurations for port 80
}